import { Product } from '@/types/product'

// Shared product data for API routes
const productsData: Product[] = [
  {
    id: 1,
    name: 'Evening Elegance Gown Design',
    price: 299,
    originalPrice: 399,
    rating: 4.8,
    reviews: 24,
    category: 'women',
    collection: 'evening',
    images: [
      'https://images.unsplash.com/photo-1595777457583-95e059d581b8?w=800&h=1000&fit=crop',
      'https://images.unsplash.com/photo-1566479179817-278b0e8e0c6a?w=800&h=1000&fit=crop',
      'https://images.unsplash.com/photo-1594633312681-425c7b97ccd1?w=800&h=1000&fit=crop',
      'https://images.unsplash.com/photo-1595777457583-95e059d581b8?w=800&h=1000&fit=crop',
    ],
    description: 'An exquisite evening gown design that captures timeless elegance. This hand-sketched design features flowing lines, sophisticated draping, and intricate detailing perfect for formal events. Purchase includes high-resolution digital files ready for production.',
    designType: 'both',
    format: ['PDF', 'PNG', 'SVG', 'AI'],
    designer: {
      name: 'Elena Martinez',
      bio: 'Master fashion designer with 15+ years of experience',
      experience: 'Former lead designer at luxury fashion houses, specializing in evening wear and formal designs',
    },
    details: {
      designStyle: 'Classic Elegant',
      complexity: 'complex',
      estimatedTime: '2-3 weeks for production',
      fileFormats: ['PDF (Print Ready)', 'PNG (High Res)', 'SVG (Vector)', 'AI (Editable)'],
      resolution: '300 DPI minimum',
      customization: 'Color variations, size adjustments, fabric suggestions included',
      license: 'Commercial use license included',
    },
    sizes: ['XS', 'S', 'M', 'L', 'XL', 'XXL'],
    colorOptions: ['Midnight Black', 'Champagne Gold', 'Deep Burgundy', 'Navy Blue', 'Ivory White'],
    highlights: [
      'Professional hand-drawn design with artisanal craftsmanship',
      'Complete technical specifications and measurements',
      'Fabric recommendations and care instructions',
      'Multiple color variations included',
      'Commercial license for production',
      'Lifetime access to design files',
    ],
    tags: ['evening', 'formal', 'elegant', 'luxury', 'gown'],
    inStock: true,
    featured: true,
    createdAt: '2024-01-15T10:00:00Z',
    updatedAt: '2024-12-01T10:00:00Z',
    similarProducts: [3, 6, 8],
  },
  {
    id: 2,
    name: 'Garden Party Floral Design',
    price: 249,
    originalPrice: 329,
    rating: 4.9,
    reviews: 18,
    category: 'girls',
    collection: 'casual',
    images: [
      'https://images.unsplash.com/photo-1515886657613-9f3515b0c78f?w=800&h=1000&fit=crop',
      'https://images.unsplash.com/photo-1594633313593-bab3825d0caf?w=800&h=1000&fit=crop',
      'https://images.unsplash.com/photo-1566479179817-278b0e8e0c6a?w=800&h=1000&fit=crop',
      'https://images.unsplash.com/photo-1515886657613-9f3515b0c78f?w=800&h=1000&fit=crop',
    ],
    description: 'A delightful garden party dress design with charming floral patterns and playful details. Perfect for young fashionistas, this design combines vibrant colors with comfortable, breathable styling ideal for parties and casual outings.',
    designType: 'both',
    format: ['PDF', 'PNG', 'SVG'],
    designer: {
      name: 'Sofia Chen',
      bio: 'Creative designer specializing in children\'s fashion',
      experience: 'Award-winning designer with expertise in playful, age-appropriate designs',
    },
    details: {
      designStyle: 'Playful Floral',
      complexity: 'moderate',
      estimatedTime: '1-2 weeks for production',
      fileFormats: ['PDF (Print Ready)', 'PNG (High Res)', 'SVG (Vector)'],
      resolution: '300 DPI',
      customization: 'Color palette variations, size range 3-14Y',
      license: 'Commercial use license included',
    },
    sizes: ['3-4Y', '5-6Y', '7-8Y', '9-10Y', '11-12Y', '13-14Y'],
    colorOptions: ['Floral Pink', 'Mint Green', 'Sunny Yellow', 'Lavender', 'Sky Blue'],
    highlights: [
      'Vibrant floral hand-drawn patterns',
      'Age-appropriate design for girls',
      'Comfortable and practical styling',
      'Multiple color combinations',
      'Easy to produce with standard fabrics',
      'Includes size grading guide',
    ],
    tags: ['casual', 'floral', 'girls', 'party', 'colorful'],
    inStock: true,
    featured: true,
    createdAt: '2024-02-10T10:00:00Z',
    updatedAt: '2024-11-20T10:00:00Z',
    similarProducts: [4, 7],
  },
  {
    id: 3,
    name: 'Modern Minimalist Dress Design',
    price: 269,
    originalPrice: 349,
    rating: 4.7,
    reviews: 31,
    category: 'women',
    collection: 'contemporary',
    images: [
      'https://images.unsplash.com/photo-1595777457583-95e059d581b8?w=800&h=1000&fit=crop',
      'https://images.unsplash.com/photo-1566479179817-278b0e8e0c6a?w=800&h=1000&fit=crop',
      'https://images.unsplash.com/photo-1594633313593-bab3825d0caf?w=800&h=1000&fit=crop',
      'https://images.unsplash.com/photo-1595777457583-95e059d581b8?w=800&h=1000&fit=crop',
    ],
    description: 'A contemporary minimalist dress design featuring clean lines and perfect proportions. This versatile design works for both professional and casual settings, embodying understated elegance and timeless style.',
    designType: 'both',
    format: ['PDF', 'PNG', 'SVG', 'AI'],
    designer: {
      name: 'Marco Rossi',
      bio: 'Architect-turned-fashion designer',
      experience: 'Known for minimalist aesthetics and functional design principles',
    },
    details: {
      designStyle: 'Minimalist Contemporary',
      complexity: 'simple',
      estimatedTime: '1-2 weeks for production',
      fileFormats: ['PDF (Print Ready)', 'PNG (High Res)', 'SVG (Vector)', 'AI (Editable)'],
      resolution: '300 DPI',
      customization: 'Color variations, fabric suggestions, styling guide',
      license: 'Commercial use license included',
    },
    sizes: ['XS', 'S', 'M', 'L', 'XL', 'XXL'],
    colorOptions: ['Charcoal Grey', 'Cream', 'Black', 'Sage Green', 'Navy'],
    highlights: [
      'Timeless minimalist design philosophy',
      'Versatile for work and casual wear',
      'Easy to produce with standard materials',
      'Multiple color options',
      'Includes styling guide',
      'Sustainable design principles',
    ],
    tags: ['minimalist', 'contemporary', 'versatile', 'professional'],
    inStock: true,
    featured: true,
    createdAt: '2024-03-05T10:00:00Z',
    updatedAt: '2024-12-05T10:00:00Z',
    similarProducts: [8, 5, 1],
  },
  {
    id: 4,
    name: 'Royal Dreams Princess Design',
    price: 279,
    originalPrice: 369,
    rating: 4.9,
    reviews: 22,
    category: 'girls',
    collection: 'formal',
    images: [
      'https://images.unsplash.com/photo-1594633312681-425c7b97ccd1?w=800&h=1000&fit=crop',
      'https://images.unsplash.com/photo-1515886657613-9f3515b0c78f?w=800&h=1000&fit=crop',
      'https://images.unsplash.com/photo-1566479179817-278b0e8e0c6a?w=800&h=1000&fit=crop',
      'https://images.unsplash.com/photo-1594633312681-425c7b97ccd1?w=800&h=1000&fit=crop',
    ],
    description: 'Every girl dreams of feeling like royalty. This stunning formal dress design brings those dreams to life with elegant tulle details, fitted bodice, and flowing skirt perfect for special occasions, weddings, and formal events.',
    designType: 'both',
    format: ['PDF', 'PNG', 'SVG'],
    designer: {
      name: 'Isabella Thompson',
      bio: 'Specialist in children\'s formal wear design',
      experience: 'Creating magical designs for special occasions for over 10 years',
    },
    details: {
      designStyle: 'Formal Princess',
      complexity: 'complex',
      estimatedTime: '2-3 weeks for production',
      fileFormats: ['PDF (Print Ready)', 'PNG (High Res)', 'SVG (Vector)'],
      resolution: '300 DPI',
      customization: 'Color variations, embellishment options, size range',
      license: 'Commercial use license included',
    },
    sizes: ['3-4Y', '5-6Y', '7-8Y', '9-10Y', '11-12Y', '13-14Y'],
    colorOptions: ['Princess Pink', 'Royal Blue', 'Elegant Purple', 'Soft White', 'Lavender'],
    highlights: [
      'Magical formal design with tulle details',
      'Hand-decorated embellishment guide included',
      'Perfect for special occasions',
      'Complete size grading for all ages',
      'Fabric and trim recommendations',
      'Makes every girl feel special',
    ],
    tags: ['formal', 'princess', 'girls', 'special-occasion', 'elegant'],
    inStock: true,
    featured: true,
    createdAt: '2024-01-20T10:00:00Z',
    updatedAt: '2024-11-15T10:00:00Z',
    similarProducts: [2, 7],
  },
  {
    id: 5,
    name: 'Summer Breeze Casual Design',
    price: 239,
    originalPrice: 299,
    rating: 4.6,
    reviews: 15,
    category: 'women',
    collection: 'casual',
    images: [
      'https://images.unsplash.com/photo-1566479179817-278b0e8e0c6a?w=800&h=1000&fit=crop',
      'https://images.unsplash.com/photo-1595777457583-95e059d581b8?w=800&h=1000&fit=crop',
      'https://images.unsplash.com/photo-1594633313593-bab3825d0caf?w=800&h=1000&fit=crop',
      'https://images.unsplash.com/photo-1566479179817-278b0e8e0c6a?w=800&h=1000&fit=crop',
    ],
    description: 'Light, airy, and absolutely perfect for warm weather. The Summer Breeze design captures the essence of carefree style with breathable fabrics and relaxed silhouettes ideal for beach outings and summer activities.',
    designType: 'both',
    format: ['PDF', 'PNG', 'SVG'],
    designer: {
      name: 'Lucia Santos',
      bio: 'Sustainable fashion design expert',
      experience: 'Focus on eco-friendly and comfortable designs',
    },
    details: {
      designStyle: 'Casual Summer',
      complexity: 'simple',
      estimatedTime: '1 week for production',
      fileFormats: ['PDF (Print Ready)', 'PNG (High Res)', 'SVG (Vector)'],
      resolution: '300 DPI',
      customization: 'Color options, fabric suggestions (organic cotton recommended)',
      license: 'Commercial use license included',
    },
    sizes: ['XS', 'S', 'M', 'L', 'XL', 'XXL'],
    colorOptions: ['Sunny White', 'Sky Blue', 'Peach', 'Mint', 'Coral'],
    highlights: [
      'Perfect for warm climates',
      'Lightweight and breathable design',
      'Eco-friendly fabric recommendations',
      'Easy to produce',
      'Comfortable for all-day wear',
      'Sustainable design approach',
    ],
    tags: ['casual', 'summer', 'beach', 'comfortable', 'sustainable'],
    inStock: true,
    featured: false,
    createdAt: '2024-04-12T10:00:00Z',
    updatedAt: '2024-10-30T10:00:00Z',
    similarProducts: [3, 8],
  },
  {
    id: 6,
    name: 'Sunset Elegance Evening Design',
    price: 319,
    originalPrice: 429,
    rating: 4.8,
    reviews: 28,
    category: 'women',
    collection: 'evening',
    images: [
      'https://images.unsplash.com/photo-1594633312681-425c7b97ccd1?w=800&h=1000&fit=crop',
      'https://images.unsplash.com/photo-1595777457583-95e059d581b8?w=800&h=1000&fit=crop',
      'https://images.unsplash.com/photo-1566479179817-278b0e8e0c6a?w=800&h=1000&fit=crop',
      'https://images.unsplash.com/photo-1594633312681-425c7b97ccd1?w=800&h=1000&fit=crop',
    ],
    description: 'Inspired by the warm hues of a beautiful sunset, this evening gown design radiates warmth and sophistication. Features luxurious silk-like draping, hand-stitched detail guides, and rich color palettes perfect for galas and special events.',
    designType: 'both',
    format: ['PDF', 'PNG', 'SVG', 'AI'],
    designer: {
      name: 'Philippe Dubois',
      bio: 'Master of evening wear design',
      experience: '20+ years creating luxury evening gown designs',
    },
    details: {
      designStyle: 'Luxury Evening',
      complexity: 'complex',
      estimatedTime: '3-4 weeks for production',
      fileFormats: ['PDF (Print Ready)', 'PNG (High Res)', 'SVG (Vector)', 'AI (Editable)'],
      resolution: '300 DPI',
      customization: 'Rich color palette, fabric recommendations, embellishment guide',
      license: 'Commercial use license included',
    },
    sizes: ['XS', 'S', 'M', 'L', 'XL', 'XXL'],
    colorOptions: ['Sunset Orange', 'Warm Amber', 'Deep Rose', 'Golden Bronze', 'Burgundy'],
    highlights: [
      'Luxurious evening gown design',
      'Rich warm color palette',
      'Detailed hand-stitching guide',
      'Premium fabric recommendations',
      'Investment piece design',
      'Complete production specifications',
    ],
    tags: ['evening', 'luxury', 'gala', 'sophisticated', 'premium'],
    inStock: true,
    featured: true,
    createdAt: '2024-01-08T10:00:00Z',
    updatedAt: '2024-12-10T10:00:00Z',
    similarProducts: [1, 3],
  },
  {
    id: 7,
    name: 'Celestial Dreams Design',
    price: 259,
    originalPrice: 339,
    rating: 4.7,
    reviews: 19,
    category: 'girls',
    collection: 'formal',
    images: [
      'https://images.unsplash.com/photo-1515886657613-9f3515b0c78f?w=800&h=1000&fit=crop',
      'https://images.unsplash.com/photo-1594633312681-425c7b97ccd1?w=800&h=1000&fit=crop',
      'https://images.unsplash.com/photo-1566479179817-278b0e8e0c6a?w=800&h=1000&fit=crop',
      'https://images.unsplash.com/photo-1515886657613-9f3515b0c78f?w=800&h=1000&fit=crop',
    ],
    description: 'A magical dress design inspired by the night sky. With celestial patterns, dreamy colors, and imaginative details, this design is perfect for imaginative girls who love to dream big. Ideal for parties, school events, and special celebrations.',
    designType: 'both',
    format: ['PDF', 'PNG', 'SVG'],
    designer: {
      name: 'Amelia Foster',
      bio: 'Creative designer specializing in imaginative children\'s wear',
      experience: 'Bringing dreams to life through design for 8+ years',
    },
    details: {
      designStyle: 'Imaginative Celestial',
      complexity: 'moderate',
      estimatedTime: '1-2 weeks for production',
      fileFormats: ['PDF (Print Ready)', 'PNG (High Res)', 'SVG (Vector)'],
      resolution: '300 DPI',
      customization: 'Celestial pattern variations, color combinations',
      license: 'Commercial use license included',
    },
    sizes: ['3-4Y', '5-6Y', '7-8Y', '9-10Y', '11-12Y', '13-14Y'],
    colorOptions: ['Midnight Blue', 'Twilight Purple', 'Starlight Silver', 'Moon White', 'Cosmic Pink'],
    highlights: [
      'Celestial hand-drawn patterns',
      'Dreamy color combinations',
      'Perfect for special celebrations',
      'Comfortable for all-day wear',
      'Age-appropriate magical design',
      'Includes pattern placement guide',
    ],
    tags: ['formal', 'celestial', 'imaginative', 'girls', 'special'],
    inStock: true,
    featured: false,
    createdAt: '2024-02-25T10:00:00Z',
    updatedAt: '2024-11-25T10:00:00Z',
    similarProducts: [4, 2],
  },
  {
    id: 8,
    name: 'Minimalist Charm Design',
    price: 245,
    originalPrice: 319,
    rating: 4.5,
    reviews: 12,
    category: 'women',
    collection: 'contemporary',
    images: [
      'https://images.unsplash.com/photo-1595777457583-95e059d581b8?w=800&h=1000&fit=crop',
      'https://images.unsplash.com/photo-1566479179817-278b0e8e0c6a?w=800&h=1000&fit=crop',
      'https://images.unsplash.com/photo-1594633313593-bab3825d0caf?w=800&h=1000&fit=crop',
      'https://images.unsplash.com/photo-1595777457583-95e059d581b8?w=800&h=1000&fit=crop',
    ],
    description: 'Simplicity is sophistication. This minimalist charm design proves that less is always more. A versatile everyday dress design that works for both work and casual settings, featuring clean lines and timeless appeal.',
    designType: 'both',
    format: ['PDF', 'PNG', 'SVG'],
    designer: {
      name: 'Henrik Larsson',
      bio: 'Minimalist design expert',
      experience: 'Specializing in clean, functional designs for modern women',
    },
    details: {
      designStyle: 'Minimalist Everyday',
      complexity: 'simple',
      estimatedTime: '1 week for production',
      fileFormats: ['PDF (Print Ready)', 'PNG (High Res)', 'SVG (Vector)'],
      resolution: '300 DPI',
      customization: 'Color variations, fabric options',
      license: 'Commercial use license included',
    },
    sizes: ['XS', 'S', 'M', 'L', 'XL', 'XXL'],
    colorOptions: ['Stone White', 'Taupe', 'Black', 'Navy', 'Charcoal'],
    highlights: [
      'Simple, elegant design',
      'Perfect everyday dress',
      'Versatile color choices',
      'Easy to produce',
      'Timeless and practical',
      'Sustainable design approach',
    ],
    tags: ['minimalist', 'everyday', 'versatile', 'practical', 'modern'],
    inStock: true,
    featured: false,
    createdAt: '2024-03-18T10:00:00Z',
    updatedAt: '2024-11-18T10:00:00Z',
    similarProducts: [3, 5],
  },
  {
    id: 9,
    name: 'Bridal Elegance Gown Design',
    price: 449,
    originalPrice: 599,
    rating: 4.9,
    reviews: 42,
    category: 'women',
    collection: 'bridal',
    images: [
      'https://images.unsplash.com/photo-1594633312681-425c7b97ccd1?w=800&h=1000&fit=crop',
      'https://images.unsplash.com/photo-1595777457583-95e059d581b8?w=800&h=1000&fit=crop',
      'https://images.unsplash.com/photo-1566479179817-278b0e8e0c6a?w=800&h=1000&fit=crop',
      'https://images.unsplash.com/photo-1594633312681-425c7b97ccd1?w=800&h=1000&fit=crop',
    ],
    description: 'A stunning bridal gown design that captures the essence of timeless romance. Features intricate lace details, flowing train, and elegant silhouette perfect for your special day. Complete with veil design suggestions and accessory recommendations.',
    designType: 'both',
    format: ['PDF', 'PNG', 'SVG', 'AI'],
    designer: {
      name: 'Victoria Rose',
      bio: 'Bridal design specialist with 20+ years of experience',
      experience: 'Creating dream wedding gowns for brides worldwide, specializing in classic and modern bridal designs',
    },
    details: {
      designStyle: 'Classic Bridal',
      complexity: 'complex',
      estimatedTime: '4-6 weeks for production',
      fileFormats: ['PDF (Print Ready)', 'PNG (High Res)', 'SVG (Vector)', 'AI (Editable)'],
      resolution: '300 DPI',
      customization: 'Full customization available, veil and accessory designs included',
      license: 'Commercial use license included',
    },
    sizes: ['XS', 'S', 'M', 'L', 'XL', 'XXL'],
    colorOptions: ['Ivory White', 'Blush Pink', 'Champagne', 'Pearl White', 'Soft Cream'],
    highlights: [
      'Exquisite bridal gown design',
      'Intricate lace and embellishment details',
      'Complete veil design included',
      'Accessory recommendations',
      'Bridal styling guide',
      'Lifetime access to design files',
    ],
    tags: ['bridal', 'wedding', 'elegant', 'romantic', 'luxury'],
    inStock: true,
    featured: true,
    createdAt: '2024-01-01T10:00:00Z',
    updatedAt: '2024-12-15T10:00:00Z',
    similarProducts: [1, 6],
  },
  {
    id: 10,
    name: 'Playful Princess Design',
    price: 229,
    originalPrice: 299,
    rating: 4.8,
    reviews: 31,
    category: 'girls',
    collection: 'casual',
    images: [
      'https://images.unsplash.com/photo-1515886657613-9f3515b0c78f?w=800&h=1000&fit=crop',
      'https://images.unsplash.com/photo-1594633312681-425c7b97ccd1?w=800&h=1000&fit=crop',
      'https://images.unsplash.com/photo-1566479179817-278b0e8e0c6a?w=800&h=1000&fit=crop',
      'https://images.unsplash.com/photo-1515886657613-9f3515b0c78f?w=800&h=1000&fit=crop',
    ],
    description: 'A fun and playful dress design perfect for active little girls. Features comfortable fit, durable design, and vibrant colors that kids love. Ideal for everyday wear, playdates, and casual occasions.',
    designType: 'both',
    format: ['PDF', 'PNG', 'SVG'],
    designer: {
      name: 'Emma Johnson',
      bio: 'Children\'s wear designer focusing on comfort and fun',
      experience: 'Creating playful, practical designs for active children',
    },
    details: {
      designStyle: 'Playful Casual',
      complexity: 'simple',
      estimatedTime: '1 week for production',
      fileFormats: ['PDF (Print Ready)', 'PNG (High Res)', 'SVG (Vector)'],
      resolution: '300 DPI',
      customization: 'Color variations, size range 2-12Y',
      license: 'Commercial use license included',
    },
    sizes: ['2-3Y', '4-5Y', '6-7Y', '8-9Y', '10-11Y', '12Y'],
    colorOptions: ['Rainbow', 'Pink Paradise', 'Blue Sky', 'Sunshine Yellow', 'Lavender Dreams'],
    highlights: [
      'Comfortable and practical design',
      'Durable construction for active play',
      'Vibrant color options',
      'Easy to produce',
      'Machine washable friendly',
      'Age-appropriate styling',
    ],
    tags: ['casual', 'playful', 'girls', 'comfortable', 'colorful'],
    inStock: true,
    featured: false,
    createdAt: '2024-03-20T10:00:00Z',
    updatedAt: '2024-11-20T10:00:00Z',
    similarProducts: [2, 7],
  },
  {
    id: 11,
    name: 'Business Professional Design',
    price: 279,
    originalPrice: 349,
    rating: 4.7,
    reviews: 28,
    category: 'women',
    collection: 'contemporary',
    images: [
      'https://images.unsplash.com/photo-1595777457583-95e059d581b8?w=800&h=1000&fit=crop',
      'https://images.unsplash.com/photo-1566479179817-278b0e8e0c6a?w=800&h=1000&fit=crop',
      'https://images.unsplash.com/photo-1594633313593-bab3825d0caf?w=800&h=1000&fit=crop',
      'https://images.unsplash.com/photo-1595777457583-95e059d581b8?w=800&h=1000&fit=crop',
    ],
    description: 'A sophisticated professional dress design perfect for the modern workplace. Features tailored fit, elegant lines, and versatile styling that transitions seamlessly from office to evening events.',
    designType: 'both',
    format: ['PDF', 'PNG', 'SVG', 'AI'],
    designer: {
      name: 'Sarah Mitchell',
      bio: 'Professional wear specialist',
      experience: 'Designing corporate and professional attire for over 12 years',
    },
    details: {
      designStyle: 'Professional Contemporary',
      complexity: 'moderate',
      estimatedTime: '1-2 weeks for production',
      fileFormats: ['PDF (Print Ready)', 'PNG (High Res)', 'SVG (Vector)', 'AI (Editable)'],
      resolution: '300 DPI',
      customization: 'Color variations, professional fabric recommendations',
      license: 'Commercial use license included',
    },
    sizes: ['XS', 'S', 'M', 'L', 'XL', 'XXL'],
    colorOptions: ['Navy Blue', 'Charcoal Grey', 'Black', 'Burgundy', 'Forest Green'],
    highlights: [
      'Professional and polished design',
      'Versatile for office and events',
      'Tailored fit specifications',
      'Professional fabric recommendations',
      'Easy to maintain',
      'Timeless professional style',
    ],
    tags: ['professional', 'business', 'contemporary', 'office', 'elegant'],
    inStock: true,
    featured: false,
    createdAt: '2024-02-15T10:00:00Z',
    updatedAt: '2024-11-15T10:00:00Z',
    similarProducts: [3, 8],
  },
  {
    id: 12,
    name: 'Fairy Tale Ball Gown Design',
    price: 329,
    originalPrice: 429,
    rating: 4.9,
    reviews: 35,
    category: 'girls',
    collection: 'formal',
    images: [
      'https://images.unsplash.com/photo-1594633312681-425c7b97ccd1?w=800&h=1000&fit=crop',
      'https://images.unsplash.com/photo-1515886657613-9f3515b0c78f?w=800&h=1000&fit=crop',
      'https://images.unsplash.com/photo-1566479179817-278b0e8e0c6a?w=800&h=1000&fit=crop',
      'https://images.unsplash.com/photo-1594633312681-425c7b97ccd1?w=800&h=1000&fit=crop',
    ],
    description: 'A magical ball gown design that brings fairy tales to life. Features voluminous tulle skirt, fitted bodice with delicate details, and enchanting styling perfect for special occasions, recitals, and formal events.',
    designType: 'both',
    format: ['PDF', 'PNG', 'SVG'],
    designer: {
      name: 'Isabella Thompson',
      bio: 'Specialist in children\'s formal wear design',
      experience: 'Creating magical designs for special occasions for over 10 years',
    },
    details: {
      designStyle: 'Fairy Tale Formal',
      complexity: 'complex',
      estimatedTime: '2-3 weeks for production',
      fileFormats: ['PDF (Print Ready)', 'PNG (High Res)', 'SVG (Vector)'],
      resolution: '300 DPI',
      customization: 'Color variations, embellishment options',
      license: 'Commercial use license included',
    },
    sizes: ['3-4Y', '5-6Y', '7-8Y', '9-10Y', '11-12Y', '13-14Y'],
    colorOptions: ['Princess Pink', 'Lavender Dreams', 'Sky Blue', 'Ivory White', 'Rose Gold'],
    highlights: [
      'Magical ball gown design',
      'Voluminous tulle skirt',
      'Delicate bodice details',
      'Perfect for special occasions',
      'Complete size grading',
      'Makes every girl feel like a princess',
    ],
    tags: ['formal', 'ball-gown', 'fairy-tale', 'girls', 'special'],
    inStock: true,
    featured: true,
    createdAt: '2024-01-25T10:00:00Z',
    updatedAt: '2024-12-05T10:00:00Z',
    similarProducts: [4, 7],
  },
]

export default productsData




